[package]
name = "rms-analysis"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rms-profile.workspace = true
rms-semantics.workspace = true
rms-source.workspace = true
rms-syntax.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
